### ISSUE TITLE
Air Wing adjustments in a running campaign

### ISSUE THREAD

**Issue by Grizzly35** [dcs-retribution/dcs-retribution#101]
### Is your feature request related to a problem? Please describe.

Currently you cannot adjust (f.e. add) new squadrons or aircrafts in a running campaign. Creating a campaign can be very frustrating when you forget an aircraft or naming etc.

### Describe the solution you'd like

Create the possibility to adjust/change/add the air wing and squadrons like in the campaign wizard within a running campaign.

**Comment by Raffson** [comment]
Initially solved by 9ff9fa5b69b7778f496b9b050de7985ef90e6bfd, further streamlining was done 👍
