### ISSUE TITLE
Weather improvement

### ISSUE THREAD

**Issue by Grizzly35** [dcs-retribution/dcs-retribution#103]
### Is your feature request related to a problem? Please describe.

Currently the weather cannot be adjusted

### Describe the solution you'd like

If possible create following functions:
- Function to adjust camapign or Turn date and time in a running campaign
- Function to adjust Time of Turn (Day)
- Function to adjust the weather with DCS weather presets

**Comment by Cathal-Brugha** [comment]
Part of campaign settings, percent chance of various weather states, such as rain, overcast, heavy clouds, light clouds, clear, and wind speed.
