### ISSUE TITLE
problems with registration plates of the F-18

### ISSUE THREAD

**Issue by jcllore** [dcs-retribution/dcs-retribution#111]
### Affected versions

v1.1

### Description

Hello, the f-18 license plates appear multiplied, this does not happen to me with the other planes. Greetings and thank you

### Save game and other files

![Screen_230416_175214](https://user-images.githubusercontent.com/32200756/232325248-a65ba84b-66db-4c17-bb91-c1dc929a3167.jpg)

**Comment by Raffson** [comment]
Thanks for reporting this issue, although I have some questions after having done some quick testing:
- Are you running the latest open beta version of DCS?
- Are you running the mission on a dedicated server?
- Does the problem persist if you change skins during the mission?

If possible, please upload a miz file where this problem manifests itself.

**Comment by jcllore** [comment]
Hi, I think it's a problem with the latest DCS update. It is not cause for retribution. Thank you

https://forum.dcs.world/topic/323960-fa-18c-board-number-error-in-the-ob-28438947/#comment-5198391

**Comment by Raffson** [comment]
> Hi, I think it's a problem with the latest DCS update. It is not cause for retribution. Thank you
> 
> 
> 
> https://forum.dcs.world/topic/323960-fa-18c-board-number-error-in-the-ob-28438947/#comment-5198391

Thanks for confirming, will close this issue as solved since this seems to be out of our control.

Please feel free to reopen the issue if this assumption turns out to be wrong. 😉
