### ISSUE TITLE
Add Spanish Navy mod

### ISSUE THREAD

**Issue by Raffson** [dcs-retribution/dcs-retribution#119]
Mod can be found here: https://www.digitalcombatsimulator.com/en/files/3309515/

EDIT: download link broken, moved here: https://desdemicabina.gumroad.com/l/qzoed?layout=profile

**Comment by Adecarcer** [comment]
Cool!!  that would be wonderful if possible.  I have a very nice campaing about Morocco trying to invade Canary Islands and the Spanish army sending the LHA Juan Carlos I and all its F-18s and Mirages F1s  Would be great if we could have the spanish naval assets in there
