### ISSUE TITLE
Selectable ground or air focus for the AI

### ISSUE THREAD

**Issue by Galwran** [dcs-retribution/dcs-retribution#123]
### Is your feature request related to a problem? Please describe.

The enemy does not make a strategic focus on any assets types. I believe it will divide the money equally on available assets.
I would rather have scenarios where the enemy has just a few MiG-29s, some attack planes but dozens and dozens of T-55s and T-72s and BMPs. 

### Describe the solution you'd like

There should be slider in the "New game - economy options" which would select the percentage of the money that the AI will spend on airplanes or ground units.

**Comment by Raffson** [comment]
There's an option to control this, it's just not available through the New Game Wizard.

Although I believe it's currently not part of the latest release, so I recommend switching over to the dev-builds. In case you're not too familiar with GitHub's Actions page, I recommend joining our discord so you can make use of our #betas channel. It will link you directly to a page where you can download the specific build.

However, iirc the procurement of forces is hard-coded for the first turn, i.e. it will always invest 70% of the budget on aircraft and 30% on ground forces. If that's what you're referring to in specific, please rename/edit the issue accordingly 😉

**Comment by Raffson** [comment]
Or are you asking for this option to be exposed in the New Game Wizard? Or perhaps both? 😂

**Comment by Raffson** [comment]
I've just verified and turns out the options are part of v1.1/v1.1.1, so I must've mixed some stuff up 😅

Either way, I know what to do 👍

**Comment by Raffson** [comment]
I think I will take it a step further and simply rework the NewGameWizard so it reuses the logic of the regular options screen. That way all settings will become available while making a new campaign, obviously including the load/save capabilities as well.
