### ISSUE TITLE
Campaigns for Helicopters 

### ISSUE THREAD

**Issue by GrEaSeLiTeNiN** [dcs-retribution/dcs-retribution#126]
### Is your feature request related to a problem? Please describe.

Hi, are there or will there be campaigns focused mainly on attack helicopters, similar to RotorOps, but in a longer campaign style?

### Describe the solution you'd like

Have a category of campaigns designed for attack helicopters.

**Comment by Raffson** [comment]
I don't think we have a campaign yet that's dedicated to helicopters, although I would start off with Battle4Area51 and deselect all aircraft in the faction overview.
In order to make proper helicopter campaigns we would need to introduce a couple of new flight types, i.e. the ability to escort helicopters with other helicopters as well as the ability for helicopters to escort ground units.
As soon as we get that done, campaigns for helicopters only will start to make a lot of sense 😁

**Comment by GrEaSeLiTeNiN** [comment]
I see, thanks for the reply :)

**Comment by Raffson** [comment]
> I see, thanks for the reply :) 

No worries, you're welcome 😉

I'll leave this issue open as a placeholder until the necessary flight-plan types have been made. Personally I don't think I'll have the spare time to create a dedicated helicopter campaign, but with what I have in mind, helicopters will have some extra work to do.
Obviously if you decide to make such a campaign, you're more than welcome to submit it to be integrated as a built-in campaign. For the same reason I would recommend joining our discord if you haven't done so already, so you can ask questions regarding campaign design if needed. 😉

**Comment by holyorangejuice** [comment]
Aleppo Insurgency has just released and it is a helicopter campaign designed by me. Should be available in the latest beta builds soon enough.

**Comment by Raffson** [comment]
Please keep in mind that it's still limited in functionality since we haven't introduced the additional logic to allow helicopters to carry out strike & escort missions.

Once I close this issue through a commit, you can expect this functionality in the upcoming beta 😉

**Comment by Raffson** [comment]
There's more then 1 helicopter campaign by now and most of the work to allow helicopters a wider variety of missions has been done, closing this issue...

**Comment by GrEaSeLiTeNiN** [comment]
Thank you!

**Comment by Raffson** [comment]
> Thank you!

For the campaigns you have mainly @holyorangejuice and @Starfire13 to thank 😁
