### ISSUE TITLE
Add Sinai support to retribution

### ISSUE THREAD

**Issue by Viper-Mav** [dcs-retribution/dcs-retribution#134]
### Is your feature request related to a problem? Please describe.

add Sinai plzz

### Describe the solution you'd like

add Sinai plzz

### Additional context

add Sinai plzz

**Comment by Raffson** [comment]
We're working on it, expecting to have a first version ready by the end of the day 🤞😉

**Comment by Viper-Mav** [comment]
Thank you, love you! You are doing a great job

**Comment by Raffson** [comment]
> Thank you, love you! You are doing a great job

Much appreciated 😉

Support for the map should be done, but obviously we need to include a couple of campaigns to get things going.

So if you have something in the works, I'd definitely be interested 😅

**Comment by Viper-Mav** [comment]
I wish i could help you, but to create campaign is beyond my skill, i'm only able to fly the plane, sryy XD

I will wait with hipe!!!

**Comment by Raffson** [comment]
> I wish i could help you, but to create campaign is beyond my skill, i'm only able to fly the plane, sryy XD
> 
> 
> 
> I will wait with hipe!!!

No worries, keep an eye out in betas channel of our discord, because most likely the next one will contain a first campaign 😉
