### ISSUE TITLE
Cheat option for moving squadrons instantly

### ISSUE THREAD

**Issue by Raffson** [dcs-retribution/dcs-retribution#14]
Mentioned in discord, it would be beneficial to have a cheat option to instantly move squadrons around airbases, preventing the need to regenerate a campaign if a mistake was made and without having to skip turns.

**Comment by holyorangejuice** [comment]
This could also be as simple as a checkbox like disable convoys. Disable ferry flights. Ferry flights never went anywhere and caused a huge issue at the airbase in build 170 on tonight's event.

**Comment by Raffson** [comment]
Not sure if the option will still be needed if the cheat option is available, but my first thought says this will be redundant.

Either way, I'll have to investigate why helicopters seems to loiter instead of actually fly to their newly assigned airbase...

**Comment by holyorangejuice** [comment]
I don't mean to add two of the same option.

Right now the convoy one is a check box. So this idea could be as well.

Or put them both in the cheat menu. But I'm not sure if these should be considered cheats. DCS AI sucks at times so I think as a checkbox option just makes more sense.

As far as them not going where they are suppose to, DCS AI won't always land where they should. I've see strike aircraft pick any random airbase if they are damaged, out of fuel or whatever other reason.
