### ISSUE TITLE
Patriots heading

### ISSUE THREAD

**Issue by Viper-Mav** [dcs-retribution/dcs-retribution#144]
### Affected versions

v1.1

### Description

The heading of the patriot sam site is stucked in one position 

### Save game and other files

https://github.com/dcs-retribution/dcs-retribution/assets/72475578/a9e4df81-82d6-4cff-83eb-fc199c0e8dcf

**Comment by Raffson** [comment]
Could you try uploading your video again? or perhaps upload it to youtube and share a private link? Because unfortunately the video is not showing on my end, so I can't really tell what's going on 😬

**Comment by Viper-Mav** [comment]
Sry, it's not a video, it's a save game file, to add a .mp4 was the only way i found to upload the save game file, forgive my noobinesh but it didn't upload the rar file :X

Just rename the file and you have the save game to check!

**Comment by Viper-Mav** [comment]
Here, i made a real video too

Only the button "head to conflict" works okay, but i can't manually change the heading:

https://github.com/dcs-retribution/dcs-retribution/assets/72475578/b08225d9-e580-4e94-bc93-bda12e60bea3

**Comment by Raffson** [comment]
This should be possible in the latest beta (courtesy of Liberation) so I recommend joining our discord for easier access to those betas.

I'll be closing the issue but feel free to reopen if you still notice something wrong in the beta build 😉
