### ISSUE TITLE
ACLS functionality is not working

### ISSUE THREAD

**Issue by WarriorX1A1** [dcs-retribution/dcs-retribution#147]
### Affected versions

v1.1

### Description

ACLS functionality is not set up on the supercarrier module.
The link 4 and ILS frequencys are correct.
Case 3 recovery, ACL button in HSI shows testing , then UTM FAIL.
I am running a preset carrier campain set in the persian gulf.  Supercarrier is enabled.

### Save game and other files

[2.zip](https://github.com/dcs-retribution/dcs-retribution/files/11779493/2.zip)

**Comment by Raffson** [comment]
I assume this is a serialization issue, any chance you could verify this by opening & resaving the mission in the editor? If that fixes the issue then I know where to start 😁

**Comment by WarriorX1A1** [comment]
It did not work by opening and resaving in M.E.

[RTest 1.zip](https://github.com/dcs-retribution/dcs-retribution/files/11779803/RTest.1.zip)

**Comment by WarriorX1A1** [comment]
It's like the carrier does not have the Advanced Waypoint / Perform Command/ Activate link4 and Perform Command/activate ACLS set up.

**Comment by Raffson** [comment]
![Screen_230617_221720](https://github.com/dcs-retribution/dcs-retribution/assets/10977187/d2e9a657-a90b-4eae-8475-f7c5fe509b6a)

I guess this explains why ACLS isn't working... let me see what needs to be done for this...

Btw, do you use the latest release? or are you using beta builds?

**Comment by Raffson** [comment]
I haven't specifically tested in-flight, but in the ME it's showing the correct frequency for link4, so I assume that's it...

If you verify the fix actually did the trick in build 491, that's be great

https://github.com/dcs-retribution/dcs-retribution/actions/runs/5300022046

**Comment by WarriorX1A1** [comment]
The name fields on the perform command window are blank. I think in Wags video they were filled in. 
this might be a solution.

**Comment by Raffson** [comment]
> The name fields on the perform command window are blank. I think in Wags video they were filled in. 
> 
> this might be a solution. 

I'd be surprised if the name is mandatory, but it's definitely worth considering in case the current fix isn't enough 👍
