### ISSUE TITLE
Support for Swedish Military Assets

### ISSUE THREAD

**Issue by Raffson** [dcs-retribution/dcs-retribution#15]
* Mod name: _**Swedish Military Assets**_
* Mod URL: https://forum.dcs.world/topic/295202-swedish-military-assets-for-dcs-by-currenthill/
* NEW MOD!

**Comment by jsharpcsa** [comment]
Would this be selectable as a mod or where would it be turned off and on?

**Comment by Raffson** [comment]
> Would this be selectable as a mod or where would it be turned off and on? 

Indeed, @MetalStormGhost should have a head start on this...

**Comment by MetalStormGhost** [comment]
Indeed. I already have the pydcs extension for this mod, but I still need the unit yamls, icons and/or banners. I haven't worked on these yet.

The mod will be selectable the same way as the Frenchpack, for example.
