### ISSUE TITLE
Plane AH-64D_BLK_II has no pylon 5

### ISSUE THREAD

**Issue by Chrischan66** [dcs-retribution/dcs-retribution#151]
### Affected versions

v1.1

### Test/Development build

1.1.1

### Description

When assigning Apache to a mission, "RuntimeError: Plane AH-64D_BLK_II has no pylon 5" pops up at TAKE OFF. 
Only local. On a dedicated server mission starts without the error.

![grafik](https://github.com/dcs-retribution/dcs-retribution/assets/56229370/63cbb2b4-a5ba-43da-bfdc-b31643a5dd1d)

### Save game and other files

.

**Comment by Raffson** [comment]
This has been solved in the dev builds, but we're not ready to release v1.2 yet.
