### ISSUE TITLE
Enemy AI not purchasing Aircraft

### ISSUE THREAD

**Issue by mcobra1588** [dcs-retribution/dcs-retribution#162]
### Affected versions

v1.2.0

### Description

Enemy AI not purchasing aircraft despite having plenty of money, available parking space, and squadron space.

### Save game and other files

[mike2.zip](https://github.com/dcs-retribution/dcs-retribution/files/11997624/mike2.zip)

**Comment by Raffson** [comment]
I'll have a look at this when I find some time.
Meanwhile, have you tried adjusting the "procurement balance ratio" in the settings?

**Comment by Raffson** [comment]
I've just verified, you could force the AI to buy more aircraft by increasing the pilot limit per squadron. It might take a turn or two to take full effect depending on the replenishment rate you set. We've increased the default to 16 pilots as a test in our dev builds to see how it affects performance with most users, but I think it'll bring some more balance to things now that MT is a thing.

**Comment by mcobra1588** [comment]
Great, will test! Thank you! 

Regarding pilots per squadron, I will try that, but with my replenishment rate, this has been happening over 4 turns so far, the AI should have full pilot squadrons, no? There are a couple squadrons with 1 aircraft.

**Comment by Raffson** [comment]
There's probably room for more improvement, but depending on the number of enemy aircraft you shot down, you may have killed most of the enemy's pilots 😅
Either way, if the issue persists after tweaking the mentioned options, feel free to reopen this issue 😉

**Comment by mcobra1588** [comment]
Just an FYI, after 4 to 5 more turns, changing those settings did not result in the AI buying even one aircraft at all. Something is up. I am sending the updated save. 
[mike2.zip](https://github.com/dcs-retribution/dcs-retribution/files/12032996/mike2.zip)

**Comment by Raffson** [comment]
Just for my understanding, are you verifying this through the intel dialog?

Also, are you skipping turns or actually playing them?

**Comment by mcobra1588** [comment]
I'm actually playing them and watching the intel dialog for reinforcements
every turn as well as checking each airbase for status

**Comment by Raffson** [comment]
Is there any chance you might be killing off the enemy faster than they can replenish? 😅

Just for science, try simply passing some turns and see how things evolve when tuning the different settings.

**Comment by mcobra1588** [comment]
No, they have not purchased even one aircraft in over 8 turns prior to me
stopping playing this campaign save
