### ISSUE TITLE
Add faction Create/Save/Edit button or dropdown menu to New Game Faction select screen.

### ISSUE THREAD

**Issue by Turbolious** [dcs-retribution/dcs-retribution#166]
### Is your feature request related to a problem? Please describe.

Just a QOL feature

### Describe the solution you'd like

Add the button to this page.

![image](https://github.com/dcs-retribution/dcs-retribution/assets/39207917/3b5cec91-23a8-414f-8c98-b483e51c1978)

**Comment by Raffson** [comment]
Might also be a good time to add a button for adding arbitrary units to a faction 👍

**Comment by Turbolious** [comment]
> Might also be a good time to add a button for adding arbitrary units to a faction 👍

100% agree, but also maybe include some text if the unit is part of a mod pack or DLC.
