### ISSUE TITLE
Tanker Frequency Missing in Briefing

### ISSUE THREAD

**Issue by holyorangejuice** [dcs-retribution/dcs-retribution#17]
### Affected versions

Test build, Development build

### Description

As requested, tested and no frequencies. Have to do an attachment to submit :P

### Save game and other files

none
![OHH CHUTE](https://user-images.githubusercontent.com/4298744/200973614-f6bc565e-78ae-49b8-a853-fb9c76bacbe0.png)

**Comment by Raffson** [comment]
Tanker info has landed 🤣
