### ISSUE TITLE
Ability to add squadrons mid-campaign 

### ISSUE THREAD

**Issue by Moguy164** [dcs-retribution/dcs-retribution#170]
### Is your feature request related to a problem? Please describe.

Yes, most of the time after I start a campaign I forget a certain aircraft that I would like to try, which often necessitates me to restart the campaign, but there's no guarantee I won't miss another aircraft. other times as the campaign evolves, I find myself wanting to fly different airframes that I didn't add at start.

### Describe the solution you'd like

The option to either change an existing squadron's aircraft, or add a new squadron with new aircraft (I was told the latter would be easier, and honestly imo, preferred)

**Comment by Raffson** [comment]
Duplicate of #101
