### ISSUE TITLE
Option to disable static aircraft

### ISSUE THREAD

**Issue by holyorangejuice** [dcs-retribution/dcs-retribution#19]
Before filing, please search the issue tracker to see if this feature has already been requested.

If requesting a DCS AI feature, check If reporting a DCS AI bug, check https://github.com/dcs-liberation/dcs_liberation#dcs-bugs.

**Is your feature request related to a problem? Please describe.**
Some people have a huge performance hit from having all the static aircraft on an airbase. I know it is part of a mission type, but one that may not be used by some.

**Describe the solution you'd like**
1 option to disable friendly static aircraft
1 option to disable enemy static aircraft

**Comment by Raffson** [comment]
Sounds like a good idea, although I'd be inclined to look at it as 1 option to disable static aircraft on both sides, which will probably be easier to implement compared to 2 separate options

**Comment by Raffson** [comment]
Completed by #37
