### ISSUE TITLE
Changing REDFOR Unit Composition on Turn Zero

### ISSUE THREAD

**Issue by Whiskey-11** [dcs-retribution/dcs-retribution#208]
### Is your feature request related to a problem? Please describe.

Not really a problem other than it forces multiple creations of a campaign to get the desired SAM networks for difficulty.

### Describe the solution you'd like

Under the current implementation, during Turn Zero (before hitting "Begin Campaign") you can edit BLUFOR unit compositions.  It would be a useful feature to edit REDFOR composition (specifically SAM sites, IMO) in the same way you can edit BLUFOR compositions.

This particular feature would be useful for fine tuning the difficulty of a campaign while utilizing mods such as High Digit SAM's where users may want to scale up or down the number/type of certain SAM's around the map to make it easier or harder.  You can currently do it with BLUFOR, but REDFOR is off limits.  

I'm not sure how difficult it would be to implement, sadly, but the basic code exists to do it for BLUFOR already and that might be useful.  For balancing purposes, maybe make it so Turn Zero REDFOR changes don't cost REDFOR any of their budget?

**Comment by Raffson** [comment]
Currently the setting acts on both coalitions. But this has been asked in the past iirc.
I'll try to implement this in the near future 😉
