### ISSUE TITLE
Specification of Air Defense units in campaign's yaml file

### ISSUE THREAD

**Issue by Raffson** [dcs-retribution/dcs-retribution#22]
A way to force certain units to start off in a campaign, allowing some more customization abilities for campaign designers.

Ideally we link unit names from the campaign's .miz file and the .yaml file.

**Comment by jsharpcsa** [comment]
I can start to research this one in the ME. A good compromise could be to have a checkbox somewhere for the units to be running or not, I assume this was referring to FLIR challenges?

**Comment by Raffson** [comment]
> I can start to research this one in the ME. A good compromise could be to have a checkbox somewhere for the units to be running or not, I assume this was referring to FLIR challenges?

I believe you're misinterpreting this one, or I haven't explained it properly 😂
The idea is to have an ability to enforce certain preset groups onto certain TGOs at the start of the campaign. For example, if you want to specifically start the campaign with an SA-10 site at a given location, say next to some enemy airbase, instead of having the campaign generator spew out stuff at random.

EDIT: random is maybe not the right term, but I find the campaign generator assigning MERAD & LORAD sites to rather weird places...

**Comment by jsharpcsa** [comment]
I get you, yes that clarifies.

**Comment by Raffson** [comment]
Example of the specification:
![image](https://user-images.githubusercontent.com/10977187/218335283-449a123a-5443-4657-8050-27f5d62d231a.png)
Where `Golan North-29` corresponds with the name of a red unit in the campaign's miz file, and SA-6 the name of a preset group. To find the name of the preset group, refer to `resources/groups`, e.g.:
![image](https://user-images.githubusercontent.com/10977187/218335386-80920e72-8c20-4b13-958f-e0bf10c1cc05.png)
Where `NASAMS AIM-120C` is the name to be used.

This suggests we'll need to scale up the number of available groups, as well as having the ability to use/read user-defined groups from the saved games folder.
