### ISSUE TITLE
Version 1.2.1 still shows as 1.2.0

### ISSUE THREAD

**Issue by GrEaSeLiTeNiN** [dcs-retribution/dcs-retribution#224]
### Affected versions

v1.2.1

### Description

I have updated to version 1.2.1 but Retribution still shows as version 1.2.0.

### Save game and other files

I have updated to version 1.2.1 but Retribution still shows as version 1.2.0.

**Comment by Raffson** [comment]
First, apologies for the late answer.
We're aware of this issue, but not planning to make a separate release for this particular problem.
This will probably be set straight when we drop v1.3, but that'll likely still take some time...
