### ISSUE TITLE
Addition to the campaign configuration file of certain options

### ISSUE THREAD

**Issue by Maveric33** [dcs-retribution/dcs-retribution#245]
### Is your feature request related to a problem? Please describe.

When we prepare the configuration file of a campaign it is always interesting to be able to prepare it as much as possible.

Except some available with the interface are not available for this file.

**Here is the list of questions:**
- No Aircraft Carriers
- No LHA
- No Player Navy
- No Enemy Navy
- Squadrons start at full capacity

### Describe the solution you'd like

Would it be possible to add and document it please.

**Comment by Raffson** [comment]
This is actually possible already:
<img width="539" alt="image" src="https://github.com/dcs-retribution/dcs-retribution/assets/10977187/8439a0f0-1634-4b8e-97f9-6044d8d824a6">

To be used as such:
![image](https://github.com/dcs-retribution/dcs-retribution/assets/10977187/6d24f142-0b67-48e2-8c3f-b09efd8dd62d)

**Comment by Maveric33** [comment]
![image](https://github.com/dcs-retribution/dcs-retribution/assets/31960224/6d0cf148-aa76-46bc-b4cd-54b395d27ada)
 i check it

**Comment by Maveric33** [comment]
Hi,
This parameter is not applied 
enable_air_wing_adjustments: true

No Error in the logs, no erreur in the interface. juste not applied at start campagne
