### ISSUE TITLE
Add automatic scheduler aggressiveness configuration for BLUEFOR

### ISSUE THREAD

**Issue by Maveric33** [dcs-retribution/dcs-retribution#246]
### Is your feature request related to a problem? Please describe.

The OPFOR aggressiveness option is truly a marvel, it allows you to script and adapt the campaign in real time, it offers a real tactical dimension. But currently we cannot make this same adjustment for the BLUEFOR which would be a real plus.

### Describe the solution you'd like

Could you integrate this same option for BLUEFOR into the Doctrine please

**Comment by Raffson** [comment]
Covered in f5bb653ad830e106a3f5b3105925882c8e9cd4a8
