### ISSUE TITLE
Add the Task Order function that we have for BLUEFOR for REDFOR

### ISSUE THREAD

**Issue by Maveric33** [dcs-retribution/dcs-retribution#251]
### Is your feature request related to a problem? Please describe.

Currently we can manipulate the Blue flights but we cannot touch those generated on the Red side. Only the level of aggression (which is already very good)

### Describe the solution you'd like

The idea would be to be able to manipulate the reds at the end of scripted missions. Of course this option should only be available if we activate it in the cheats.
I would see a system on the main page with 2 tabs like we have in Manage faction

![Capture d'écran 2024-02-11 164004](https://github.com/dcs-retribution/dcs-retribution/assets/31960224/1dacf4de-fe91-4128-af59-6a7184d6737c)

**Comment by Raffson** [comment]
Was covered a few months back...
