### ISSUE TITLE
Factions not showing on dev build f54993f

### ISSUE THREAD

**Issue by N1v0k** [dcs-retribution/dcs-retribution#261]
### Affected versions

Development build

### Test/Development build

https://github.com/dcs-retribution/dcs-retribution/actions/runs/7955710923/artifacts/1255660047

### Description

On a fresh retribution install, only WW2 and PMC factions are shown when creating a new mission. factions in `ressources/factions` and `Saved Games/DCS/Retribution/Factions` are ignored 

### Save game and other files

![image](https://github.com/dcs-retribution/dcs-retribution/assets/11612884/cb0015de-7273-4cc1-a5ca-2ef6672c36f3)

**Comment by Raffson** [comment]
Build 897 is currently the last stable version. I'm about to have a look into it & fix yesterday's screw-up 😅

**Comment by N1v0k** [comment]
Really appreciate your work, love retribution!

**Comment by Raffson** [comment]
> Really appreciate your work, love retribution!

At your service 🫡

Turns out it was a change in the pydcs layer that caused the layouts to fail during deserialization. The fix was deployed in build 904 😉
