### ISSUE TITLE
wine: Couldn't detect any installed DCS World Version

### ISSUE THREAD

**Issue by N1v0k** [dcs-retribution/dcs-retribution#280]
### Affected versions

v1.3.1

### Description

Hi!

I'm using https://github.com/Aterfax/DCS-World-Dedicated-Server-Docker to run my DCS dedicated server on a Linux Machine via docker & wine. 

This works out of the box very well and since Linux machines are so much cheaper, I'd like to use it with retribution.

However when I start the retribution also via wine i get this error:

```
dcs-world-dedicated-server:~/.wine/drive_c/users/abc/Saved Games/DCS.release_server/dcs-retribution$ wine retribution_main.exe 
0088:err:wineusb:usb_init Failed to initialize libusb: Other error
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0024:fixme:file:server_get_file_info Unsupported info class e
0024:fixme:file:server_get_file_info Unsupported info class e
0024:err:kerberos:kerberos_LsaApInitializePackage no Kerberos support, expect problems
0024:err:winediag:ntlm_check_version ntlm_auth was not found. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
0024:err:ntlm:ntlm_LsaApInitializePackage no NTLM support, expect problems
2024-04-05 20:46:52,547 :: root :: INFO :: DCS Retribution 1.3.1
2024-04-05 20:46:52,550 :: root :: DEBUG :: Python version 3.10.11 (tags/v3.10.1
1:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Couldn't detect any installed DCS World version
Couldn't detect any installed DCS World version
Couldn't detect any installed DCS World version
Couldn't detect any installed DCS World version
Couldn't detect any installed DCS World version
Couldn't detect any installed DCS World version
2024-04-05 20:46:52,675 :: uvicorn.error :: INFO :: Started server process [32]
2024-04-05 20:46:52,677 :: uvicorn.error :: INFO :: Waiting for application star
tup.
2024-04-05 20:46:52,680 :: uvicorn.error :: INFO :: Application startup complete
.
2024-04-05 20:46:52,683 :: uvicorn.error :: ERROR :: [Errno 10049] error while a
ttempting to bind on address ('::1', 16880, 0, 0): windows error 0x2741
2024-04-05 20:46:52,685 :: uvicorn.error :: INFO :: Waiting for application shut
down.
2024-04-05 20:46:52,688 :: uvicorn.error :: INFO :: Application shutdown complet
```

Now I know that you won't support wine, but it would be great to have the ability to specify the installation location in advance.
Do you think this is possible?

Thanks!

### Save game and other files

[error.log](https://github.com/dcs-retribution/dcs-retribution/files/14889650/error.log)

**Comment by Raffson** [comment]
Certainly sounds interesting. I'll try to investigate the possibilities this weekend but if you don't hear back from me by next weekend, don't hesitate to give me a ping 😉

**Comment by Raffson** [comment]
`Couldn't detect any installed DCS World version` is basically indicating that the preferences file isn't found and that pydcs can't determine a location either. Looking at the code a lot depends on what location you get back when you execute `os.environ["LOCALAPPDATA"]`, and since I'm not sure what'll be returned on Linux I'd like to ask you if it would be possible to run the following script on your server:
```
import os

print(os.environ["LOCALAPPDATA"])
```

Depending on what you get back in that script, try creating a DCSRetribution folder in that directory and create a file called retribution_preferences.json, after which you should open the file and configure it as follows:
```
{
  "saved_game_dir": "<path to SavedGames directory>",
  "dcs_install_dir": "<path to DCS installation directory>",
  "last_save_file": "",
  "ignore_empty_install_directory": <true or false, you may want to play with this...>,
  "prefer_liberation_payloads": <true or false, at your discretion>,
  "server_port": <port on which you want to run Retribution>
}
```
Let me know whether that solves anything...

**Comment by N1v0k** [comment]
This helped a lot, I could place the file to `/config/.wine/drive_c/users/abc/AppData/Local/DCSRetribution/` now the error is gone!

However I'm now stuck with this one:
```
[Errno 10049] error while attempting to bind on address ('::1', 16880, 0, 0): windows error 0x2741
```

I've already tried changing ports, it says that it tries to bind on the new port but with the same result.
Also the port isn't used by anything else.

What is this port used for?

I also tried to compile the application natively on linux, but got stuck. I've seen that there is a client installed by npm and run on port 3000, what is this exactly? Do you plan including browser support? Would be awesome.

Update:
```
export SERVER_BIND_ADDRESS=0.0.0.0
```

Fixes the issue and retribution is starting up as expected

**Comment by N1v0k** [comment]
So via `RETRIBUTION_EXPORT_DIR` I can now see the state.json which is also getting updated properly. 
This is already a huge achievement for me, because I can now run a DCS Server with Retribution inside a docker container within minutes on a cheap beefy linux server!!

However when I imported the state.json it didn't display the results correctly, but I'm not sure if it's a display (font) issue.

The icing on the cake would be if retribution would detect the the mission state automatically, which it isn't atm.
So my question is:

1. What is the service  on port 16880 supposed to do? Is it responsible for mission state sync?
2. Will the retribution QT app look at RETRIBUTION_EXPORT_DIR and import the state from there?


Thanks!

**Comment by Raffson** [comment]
1. The port is used by Retribution to host a server locally to which the map can connect (the map is a separate front-end). You can try using a different port by setting the preference, but I would be surprised if the port is already taken.

2. Normally it should, let me know if it doesn't 😅

Edit: have you checked whether the MissionScripting.lua file is properly adjusted? As in, are the sanitization lines commented out?

**Comment by Gmentsik** [comment]
It seems that the qt app is not recognizing the environment variable. 

The Missionscripting.lua is modified, the server is able to write the state.json to the path provided by the env var.

As soon as I copy the state.json to the same directory where retribution_main.exe is located, it detects it and shows the Waiting for mission completion screen.

The env var is set globally. I'll try to fix this with a file link for now, or I'll just tell the server to write the state to the folder where retribution is installed.

Next problem is that it seems some fonts are missing:

![Screenshot_20240408_222037.jpg](https://github.com/dcs-retribution/dcs-retribution/assets/11612884/a6cdb5c5-8c43-4082-bd7d-04fa7df3f5a8)

Can you tell which fonts are needed for the QT app?

Man I'm so happy this is working! This screenshot is from the browser on my phone, crazy!

**Comment by N1v0k** [comment]
It seems that the qt app is not recognizing the environment variable. 

The Missionscripting.lua is modified, the server is able to write the state.json to the path provided by the env var.

As soon as I copy the state.json to the same directory where retribution_main.exe is located, it detects it and shows the Waiting for mission completion screen.

The env var is set globally. I'll try to fix this with a file link for now, or I'll just tell the server to write the state to the folder where retribution is installed.

~~Next problem is that it seems some fonts are missing:~~

![Screenshot_20240408_222037.jpg](https://github.com/dcs-retribution/dcs-retribution/assets/11612884/a6cdb5c5-8c43-4082-bd7d-04fa7df3f5a8)

~~Can you tell which fonts are needed for the QT app?~~

Man I'm so happy this is working! This screenshot is from the browser on my phone, crazy!

Edit:
Turned out it's just some wine config issue , scaling the dpi displays everything correctly.


This means: we can now run retribution on a dedicated DCS Server on Linux via docker-compose accessible via Browser!

This is some serious sh*t. I'll do write up here, you can put it in the Wiki if you want.

**Comment by Raffson** [comment]
This is definitely interesting stuff! Glad it all worked out 😁

Btw, are you in our discord?

**Comment by N1v0k** [comment]
Sure ping me as @n1v0k

**Comment by N1v0k** [comment]
~~So I was celebrating too early ... launching a mission works with only AI flights, but when I add a player flight the kneeboard fails to generate:~~

![image](https://github.com/dcs-retribution/dcs-retribution/assets/11612884/cbe69886-0ed7-47d2-bdaa-cde217642fd3)

~~I'd guess some fonts are missing but it doesn't really say which ones, freetype should be installed however.
Do you have a educated guess what's missing?~~

Update:
`courbd.ttf` accessed by `game/missiongenerator/kneeboard.py` was missing, solved by copying courbd.ttf from a windows installation to the wine installation (Windows/Fonts)

Not sure if I can include this in a docker image, I need to research the license for this font if I'm allowed to distribute it...

**Comment by Raffson** [comment]
Worst case scenario we can change the font to something that complies with our needs 😉

**Comment by N1v0k** [comment]
I think if there is demand from the community, it would be easier to just take any open source font, that I can include and distribute in a docker image. Otherwise users will need to copy the font from their Windows Installation which makes everything complicated and non automated. 

According to this resource  https://learn.microsoft.com/en-us/typography/fonts/font-faq I'd say it isn't allowed. So a open sourced font would be better.

Yesterday I flew some missions and everything worked perfectly. 

I'll now make a GitHub repo with instructions and the code.

The icing on the cake would be if retribution could somehow support:

- "Take off" on app launch (server start)
- automatic "Take off" on mission end (server stop/restart)

Or even automatic end of the mission after specific objective complete, player rtb or timer and create a new mission and tell the server to run it. 

Haven't looked into it, but the server can be controlled via web interface, so there might be a rest interface too.

But I could imagine writing an external app for that would work too, since the state.json file could be the interface to retribution. 

But it's only nice to have, since everything is controlled in the Browser now.

**Comment by N1v0k** [comment]
I think we can close this issue, I'm in contact with Aterfax from the other repo, if we can't resolve the font issue, I'll open a new one.

Thanks for your help!

**Comment by N1v0k** [comment]
Just for reference: the pull request can be found here and will be eventually pulled into Artefax' project, there is also a sample docker-compose file and a test build if someone is eager trying this out:

https://github.com/Aterfax/DCS-World-Dedicated-Server-Docker/pull/47
