### ISSUE TITLE
Update for <Kutaisi to Vaziani>

### ISSUE THREAD

**Issue by holyorangejuice** [dcs-retribution/dcs-retribution#31]
[Kutaisi to Vaziani.zip](https://github.com/dcs-retribution/dcs-retribution/files/10163070/Kutaisi.to.Vaziani.zip)

Kutaisi to Vaziani with miz, yaml and custom factions. This campaign is ready to be added to retribution. It was fully tested by my group on 12/05/22.

**Comment by Raffson** [comment]
It seems like the blue faction is exactly the same as `wrl_taskforceblue`, so I've recycled it.
For red I still see differences so I'm leaving that as it is.
