### ISSUE TITLE
Mbot Artillery plugin does not function in Pretense

### ISSUE THREAD

**Issue by tchession** [dcs-retribution/dcs-retribution#414]
### Affected versions

Test build

### Test/Development build

#1465

### Description

When starting a generated Pretense mission with the Mbot plugin enabled, the server throws a mission script error:

"[string "I10m/DEFAULT/artymbot-config.lua']:14: attempt to index field 'artilleryGroups' (a nil value)
stack traceback: [C]:? [string "I10m/DEFAULT/artymbot-config.lua']:14: in main chunk"

The user can click OK on the mission script error and the mission will start normally, albeit with none of the Mbot F10 items available.

### Save game and other files

[pretense_campaign.zip](https://github.com/user-attachments/files/17667193/pretense_campaign.zip)

**Comment by Raffson** [comment]
Should've been fixed in the last build, but feel free to reopen the ticket if it's not the case 😉
