### ISSUE TITLE
CTLD pickup areas spawn on taxiways, in buildings, in hangars, etc

### ISSUE THREAD

**Issue by holyorangejuice** [dcs-retribution/dcs-retribution#46]
### Affected versions

Test build

### Test/Development build

Build 170

### Description

CTLD blue smoke pickup areas spawn in bad places around airbases. This causes issues with taxiways being blocked. Or the AI air assault trying to land near them and blowing up. 

### Save game and other files

![Screen_221219_194829](https://user-images.githubusercontent.com/4298744/208805815-211e7803-c4e2-4761-af86-b466eff1fd74.jpg)
![Screen_221219_194836](https://user-images.githubusercontent.com/4298744/208805818-4dd01d9c-3666-4c81-a1c2-d27a7fcca55d.jpg)
![Screen_221220_202313](https://user-images.githubusercontent.com/4298744/208805819-55ccf4c0-4eca-456d-8377-78e1448d5fdb.jpg)
![Screen_221220_202315](https://user-images.githubusercontent.com/4298744/208805822-e367274a-1dcc-4df5-a668-fbee00a38aaf.jpg)

**Comment by Raffson** [comment]
Hmmm, lovely 😂

I'm afraid we won't get to this in v1.0, so I'll add it to v1.1 & hopefully find an obvious reason to what's causing this...

**Comment by holyorangejuice** [comment]
Not sure how it's done to place the objects. Seems like a pain to exclude certain areas.

For a player it isn't as bad because you only have to land within the area. But the AI land point is nearly inside the object and smoke. So they get super close to it.

**Comment by Raffson** [comment]
How about we handle this as part of campaign design, say designate a specific zone for a CP where CTLD stuff should spawn?

**Comment by holyorangejuice** [comment]
Sounds like the reasonable option
