### ISSUE TITLE
Restore C-130 Hercules mod's Air Assault ability

### ISSUE THREAD

**Issue by Raffson** [dcs-retribution/dcs-retribution#49]
### Is your feature request related to a problem? Please describe.

After Liberation's restriction, air assaults are only available to helicopters

### Describe the solution you'd like

we need to at least re-introduce support for the Hercules mod...

**Comment by kevstosmart** [comment]
I would do some testing with AI, I have not ever had AI with preloaded paratroopers do drops.

Edit: as for player using them with the herc cargo script. Works well I also tend to use combined arms to move them but with some scripting I’m sure it can be automated

**Comment by Raffson** [comment]
If it's just a matter of injecting a script then we should be good, though we should indeed test this with AI to make sure it's not a dud :p

**Comment by kevstosmart** [comment]
10-4, reason iirc something with having preloaded troops causing issues, after holidays ill be back on the rig and start getting back into it, been running a forked version of retribution via pycharm

**Comment by Raffson** [comment]
> I would do some testing with AI

Just did a couple of tests, this should definitely work, though I'll have to look at how air assaults are set up, planes obviously behave a little different than helicopters 😂
