### ISSUE TITLE
C130 Hercules mod needs icon & banner

### ISSUE THREAD

**Issue by holyorangejuice** [dcs-retribution/dcs-retribution#51]
### Affected versions

1.0.0

### Test/Development build

1.0 release

### Description

C130 Mod Needs a Picture in Air Wing Config. Possible that other mods need a picture too.

### Save game and other files

![c130](https://user-images.githubusercontent.com/4298744/209485033-5efe47a1-e682-46a1-8e89-05abb9900623.png)

**Comment by Raffson** [comment]
Banner is also missing, any change you feel like making a 720x360 screenshot of the Hercules? 🤣 
I already have the icon locally, might as well throw in the banner while at it...
