### ISSUE TITLE
Livery Override Doesn't Always Default to Override

### ISSUE THREAD

**Issue by holyorangejuice** [dcs-retribution/dcs-retribution#52]
### Affected versions

1.0.0

### Test/Development build

1.0 release

### Description

I click on new mission wizard, I get to the air wing config, the livery section. It shows a default picked skin and I have to manually change it. Now I can't tell if this is a UI only bug. Meaning will that mi24 spawn with syria camo or will it spawn with livery override if I don't manually change it. I'm thinking since it shows me Syria camo, that is how it will spawn, instead of the override unless I change it manually to override. 

### Save game and other files

![asdf1](https://user-images.githubusercontent.com/4298744/209485891-64bdcaac-756a-4459-b17a-c5e89fe4f169.png)
![asdf2](https://user-images.githubusercontent.com/4298744/209485892-0d6e6781-69a5-42c3-adeb-5842288fcd2c.png)
![livery 2](https://user-images.githubusercontent.com/4298744/209485895-007cff1d-39ef-4496-bb21-02367827de45.png)

**Comment by holyorangejuice** [comment]
![mi8](https://user-images.githubusercontent.com/4298744/209485983-4061e630-76bf-4280-b4c2-4e8c927ee940.png)
![su25t](https://user-images.githubusercontent.com/4298744/209485987-b2ce4b2b-29f4-4713-9925-8a7b6ddbe113.png)
This is how these default load. Mi8 doesn't work without manual change. SU25t worked.

**Comment by holyorangejuice** [comment]
Confirmed, not just a UI bug, if you don't manually select the livery or the use livery overrides, it uses the wrong skin.

**Comment by Raffson** [comment]
> Confirmed, not just a UI bug, if you don't manually select the livery or the use livery overrides, it uses the wrong skin.

Wdym uses the wrong skin? Isn't it using what's selected by default?

**Comment by holyorangejuice** [comment]
> > Confirmed, not just a UI bug, if you don't manually select the livery or the use livery overrides, it uses the wrong skin.
> 
> Wdym uses the wrong skin? Isn't it using what's selected by default?

Take a look at the screenshots above. The faction is set for livery over ride. When you get to the Air Wing Config, it doesn't always over ride unless you click the drop down and find the 'use livery overrides' option. It should default to use livery over ride if you set it up that way.  It defeats the purpose if it doesn't work. If I wanted to click and drop down to find a skin I could do that. instead of edit the faction to do it for me. (which right now doesn't work)

**Comment by Raffson** [comment]
Ok so the first thing that sticks out is the Mi-8 & Mi-24 squadrons use presets, not sure why but that's definitely the cause

**Comment by holyorangejuice** [comment]
> Ok so the first thing that sticks out is the Mi-8 & Mi-24 squadrons use presets, not sure why but that's definitely the cause

The only one that worked was the SU-25t. The mi-8 and mi-24 did not. That is what I was showing.

**Comment by Raffson** [comment]
Makes sense since the Su-25T hasn't got any squadrons defined in `resources/squadrons`.
I'll have another look at it tomorrow, now that I know what the issue is I can start thinking about a proper solution for this, because it definitely conflicts with selecting preset squadrons, which iirc is the first source to choose from when it comes to populating the air wing config dialog.

**Comment by holyorangejuice** [comment]
So would a temp fix be to delete the squadrons of aircraft I want to override?

**Comment by Raffson** [comment]
> So would a temp fix be to delete the squadrons of aircraft I want to override? 

Probably that'll work. But I believe I have a solution in mind that'll fix this.

In a nutshell, if livery overrides have been detected for a certain aircraft, no squadrons should be used by the algorithm that populates the air wing config. Only when a user adds a squadron manually, using one of the presets, it should override the livery overrides.

**Comment by Raffson** [comment]
I have a local fix, so this is going to be closed soon. Here's the verdict:

> Avoid choosing random squadrons so that livery overrides takes precedence by default (if present of course) for a given aircraft type, unless the campaign file specifies a specific squadron. Users can still add a squadron manually which will automatically set the correct livery if they use a squadron preset.
