### ISSUE TITLE
CAP Return blocking airport

### ISSUE THREAD

**Issue by jsharpcsa** [dcs-retribution/dcs-retribution#58]
### Affected versions

Test build

### Test/Development build

https://github.com/dcs-retribution/dcs-retribution/actions/runs/3814230005

### Description

MiGs on return from CAP taxied into another flight that I am assuming was taxiing to relieve them. 

I am unsure if this could be reproduced reliably. It could be considered one of those one-off DCS things.

![Screen_221231_230855](https://user-images.githubusercontent.com/86506228/210162862-56c8ef42-96b7-4613-8c1f-c2a9549ae4a5.jpg)
![Screen_221231_230938](https://user-images.githubusercontent.com/86506228/210162863-6668407b-ee9b-40ae-b517-ff25f90f1346.jpg)
![Screen_221231_230952](https://user-images.githubusercontent.com/86506228/210162864-2f663a1a-d0fe-4597-97fe-0cfaa4538e2f.jpg)
![Screen_221231_230955](https://user-images.githubusercontent.com/86506228/210162865-0018d7ee-168b-43f3-86d7-78d8e9f2ef5b.jpg)

### Save game and other files
Liberation Save, Track and Miz
[DCS.openbeta.zip](https://github.com/dcs-retribution/dcs-retribution/files/10328416/DCS.openbeta.zip)
[DCS.openbeta (2).zip](https://github.com/dcs-retribution/dcs-retribution/files/10328417/DCS.openbeta.2.zip)

Rename second file to "DCS.openbeta.z01" before extracting.

**Comment by Raffson** [comment]
This looks like it's out of our hands. Essentially this is a DCS AI pathing issue...
