### ISSUE TITLE
Waypoints corrupt after deletion

### ISSUE THREAD

**Issue by jsharpcsa** [dcs-retribution/dcs-retribution#60]
### Affected versions

Development build

### Test/Development build

https://github.com/dcs-retribution/dcs-retribution/actions/runs/3814230005

### Description

When I am editing a package
![image](https://user-images.githubusercontent.com/86506228/210163469-449c0eab-caa1-4d30-877b-dae7e6770361.png)

Editing the A-10's flight, when I delete the refuel WP, TOT stops working or calculating
![image](https://user-images.githubusercontent.com/86506228/210163498-79231355-1db7-4519-8fbc-57e7fef93af9.png)

Even rebuilding the profile by resetting it to strike does nothing. The entire flight has to be deleted, meaning you are essentially stuck with a AAR point.

This happened during turn 2 setup in the Battle of Golan campaign using an A-10 to form a strike (with JF-17 escort) on target Kiwi.

### Save game and other files

[tmpsave.zip](https://github.com/dcs-retribution/dcs-retribution/files/10328460/tmpsave.zip)

**Comment by Raffson** [comment]
This is frustrating indeed. It basically has to do with the way "custom flightplans" are implemented and how regular flights are degraded when adding/deleting a waypoint.

I've looked at this not too long ago, and while it's definitely something we should tackle, I'm not sure if it's something we should plan for v1.1, but maybe for v1.2?

@MetalStormGhost what do you think?
