### ISSUE TITLE
UI did not match the outcome of the JSON file

### ISSUE THREAD

**Issue by holyorangejuice** [dcs-retribution/dcs-retribution#75]
### Affected versions

Test build, Development build

### Test/Development build

https://github.com/dcs-retribution/dcs-retribution/actions/runs/3862179820

### Description

The UI, map can glitch out and be laggy. Unsure if this is part of the issue.

We were doing an event tonight. We killed off some SAM sites, some ships, air units, and so on. The JSON file when loaded from our dedicated server showed us the debrief screen of all the kills. The in game UI only showed the ships being dead. It showed all the SAM sites being perfectly normal.

I reloaded the save and retribution. Pulled the JSON again with the same results. Not just a UI bug. 

### Save game and other files

[devbug.zip](https://github.com/dcs-retribution/dcs-retribution/files/10398229/devbug.zip)

**Comment by Raffson** [comment]
Concluded as a transient error...
