### ISSUE TITLE
Disable Convoys Option does not disable shipping convoys

### ISSUE THREAD

**Issue by holyorangejuice** [dcs-retribution/dcs-retribution#76]
### Affected versions

Development build

### Description

Disable convoys gets rid of ground convoys but does not get rid of shipping convoys. 

### Save game and other files

.

**Comment by MetalStormGhost** [comment]
Shipping convoys should only consist of a single ship per route (per direction). So the performance impact should be minimal?

**Comment by holyorangejuice** [comment]
Should be minimal and not a high priority but it was an observation.

**Comment by Raffson** [comment]
Fixed locally by adding an additional option "Disable cargo-ships"
