### ISSUE TITLE
Add/update <F18 Super Hornet 2.1>

### ISSUE THREAD

**Issue by holyorangejuice** [dcs-retribution/dcs-retribution#77]
* Mod name: F18 Super Hornet ~2.0~ 2.1
* Mod URL: https://discord.gg/eRbegB43fS
* Update or new mod? - New to retribution I think

**Comment by holyorangejuice** [comment]
This mod appears to have a host of issues and might not be worth the hassle unless they fix stuff.

![300c41d7a36ffe28a1fc19ea5af8043a](https://user-images.githubusercontent.com/4298744/212166569-b9e6e32b-1ff6-4026-906d-59dfe40614ad.png)

**Comment by Raffson** [comment]
Agreed, consider this low priority for now 👍
