### ISSUE TITLE
Add/update <F16 Sufa Mod 3.1>

### ISSUE THREAD

**Issue by holyorangejuice** [dcs-retribution/dcs-retribution#78]
* Mod name: F16 Sufa Mod 3.1
* Mod URL: https://discord.gg/45SYX3fqHU
* Update or new mod? Update

**Comment by Raffson** [comment]
@MetalStormGhost I guess I'll assign you to this?

**Comment by MetalStormGhost** [comment]
> @MetalStormGhost I guess I'll assign you to this?

I self-assigned :)
